### PR TITLE
Added my pet- Puchu (Dog)

### PR DESCRIPTION
**Pull request by shruti-sen2004**
Hello Sir,
I have added details and image of my pet dog- Puchu. Please merge my pull request.

### CODE REVIEW

**Comment by Souvik2376** [comment]
@shruti-sen2004 Update the repo by sync fork and create PR again😊

**Comment by shruti-sen2004** [comment]
@Souvik2376 I have resolved the conflict............ can you check and let me know?

**Comment by Souvik2376** [comment]
Ok || Please tell others to contribute here as well || Give a star to the repo if u like || 😊

**Comment by shruti-sen2004** [comment]
Yah surely I will tell my friends about this repo. :)

**Pull request merged**
